CREATE DATABASE products;
USE products;
CREATE TABLE Category(
  id INT(100) NOT NULL AUTO_INCREMENT,
  name CHAR (32) NOT NULL,
  CONSTRAINT PK_product PRIMARY KEY (id)
);
CREATE TABLE product(
  product_id INT(100) NOT NULL AUTO_INCREMENT,
  name CHAR (32) NOT NULL,
  price CHAR (100) NOT NULL,
  weight INT (100) NOT NULL,
  id INT(100) NOT NULL,
  CONSTRAINT PK_product PRIMARY KEY (product_id),
  CONSTRAINT FK_product FOREIGN KEY (id) REFERENCES Category (id) ON DELETE CASCADE ON UPDATE CASCADE
);