CREATE DATABASE products;
USE products;
CREATE TABLE Category(
  id INT(100) NOT NULL AUTO_INCREMENT,
  name VARCHAR (32) NOT NULL,
  CONSTRAINT category_unique UNIQUE (id),
  CONSTRAINT PK_product PRIMARY KEY (id)
);
CREATE TABLE product(
  id INT(100) NOT NULL AUTO_INCREMENT,
  name VARCHAR (32) NOT NULL,
  price INT (100) NOT NULL,
  weight INT (100) NOT NULL,
  category_id INT(100) NOT NULL,
  CONSTRAINT PK_product PRIMARY KEY (id),
  CONSTRAINT FK_product FOREIGN KEY (category_id) REFERENCES Category (id) ON DELETE CASCADE ON UPDATE CASCADE
);